In [1]:
import numpy as np
import plotly.graph_objects as go
import matplotlib.cm as cm
import matplotlib.colors as colors
from pathlib import Path
import pickle
import xarray as xr
from tqdm.notebook import tqdm

In [9]:
# read data
PROJECT_ROOT = Path.cwd().parent
pkl_file=PROJECT_ROOT/"result/run_approach.pkl"

with open(pkl_file, "rb") as f:
    obj = pickle.load(f, encoding="latin1")

    # 提取所需变量并转为 numpy array
    density = np.asarray(obj['densities'])
    reference_levels = np.asarray(obj['reference_levels'])
    score_refden = np.asarray(obj['scores_refden'])
    score_regul = np.asarray(obj['scores_regul'])
    regul = np.asarray(obj['regul_params'])
    regul_residual = np.asarray(obj['regul_residuals'])
    refden_residual = np.asarray(obj['refden_residuals'])

    refden_moho_grid = obj['best_solutions_refden_moho_grid']
    refden_predict_grid = obj['best_solutions_refden_predict_grid']
    observe = obj['observe']
    lon = obj['lon']
    lat = obj['lat']
    lon_sub = obj['lon_sub']
    lat_sub = obj['lat_sub']
    
nlat_moho, nlon_moho = refden_moho_grid.shape
lon_moho = np.linspace(lon.min(), lon.max(), nlon_moho)
lat_moho = np.linspace(lat.min(), lat.max(), nlat_moho)

moho_grid = xr.DataArray(
    refden_moho_grid,  # 如果图东西颠倒或拉伸，改为 refden_moho_grid.T
    dims=("lat", "lon"),
    coords={"lat": lat_moho, "lon": lon_moho}
)

In [11]:
moho_grid.values=moho_grid.values*1e-3+40

In [12]:
moho_grid

<xarray.DataArray (lat: 90, lon: 180)> Size: 130kB
array([[-0.42627388, -0.49708278, -0.56670523, ..., -0.20914761,
        -0.28209423, -0.35452533],
       [ 8.67342042,  8.29928798,  7.93179573, ...,  9.71619941,
         9.39665506,  9.04376079],
       [ 3.03970891,  3.43402962,  3.90458474, ...,  2.8253701 ,
         2.6967986 ,  2.77922863],
       ...,
       [-6.10723752, -5.81995915, -5.45877361, ..., -4.17580922,
        -5.32408676, -6.03319229],
       [-4.86120838, -4.69582277, -4.44402877, ..., -4.4832333 ,
        -4.73947251, -4.8795703 ],
       [ 1.49659944,  1.4327067 ,  1.38576713, ...,  1.77327579,
         1.66972052,  1.57641465]], shape=(90, 180))
Coordinates:
  * lat      (lat) float64 720B -89.5 -87.5 -85.5 -83.5 ... 82.5 84.5 86.5 88.5
  * lon      (lon) float64 1kB -179.5 -177.5 -175.5 -173.5 ... 174.5 176.5 178.5

In [5]:
moho_grid.lon

<xarray.DataArray 'lon' (lon: 180)> Size: 1kB
array([-179.5     , -177.5     , -175.5     , -173.5     , -171.5     ,
       -169.5     , -167.5     , -165.5     , -163.5     , -161.500001,
       -159.500001, -157.500001, -155.500001, -153.500001, -151.500001,
       -149.500001, -147.500001, -145.500001, -143.500001, -141.500001,
       -139.500001, -137.500001, -135.500001, -133.500001, -131.500001,
       -129.500001, -127.500001, -125.500002, -123.500002, -121.500002,
       -119.500002, -117.500002, -115.500002, -113.500002, -111.500002,
       -109.500002, -107.500002, -105.500002, -103.500002, -101.500002,
        -99.500002,  -97.500002,  -95.500002,  -93.500002,  -91.500002,
        -89.500003,  -87.500003,  -85.500003,  -83.500003,  -81.500003,
        -79.500003,  -77.500003,  -75.500003,  -73.500003,  -71.500003,
        -69.500003,  -67.500003,  -65.500003,  -63.500003,  -61.500003,
        -59.500003,  -57.500003,  -55.500003,  -53.500004,  -51.500004,
        -49.500004,  -47.500004,  -45.500004,  -43.500004,  -41.500004,
        -39.500004,  -37.500004,  -35.500004,  -33.500004,  -31.500004,
        -29.500004,  -27.500004,  -25.500004,  -23.500004,  -21.500004,
        -19.500004,  -17.500005,  -15.500005,  -13.500005,  -11.500005,
         -9.500005,   -7.500005,   -5.500005,   -3.500005,   -1.500005,
          0.499995,    2.499995,    4.499995,    6.499995,    8.499995,
         10.499995,   12.499995,   14.499995,   16.499995,   18.499994,
         20.499994,   22.499994,   24.499994,   26.499994,   28.499994,
         30.499994,   32.499994,   34.499994,   36.499994,   38.499994,
         40.499994,   42.499994,   44.499994,   46.499994,   48.499994,
         50.499994,   52.499994,   54.499993,   56.499993,   58.499993,
         60.499993,   62.499993,   64.499993,   66.499993,   68.499993,
         70.499993,   72.499993,   74.499993,   76.499993,   78.499993,
         80.499993,   82.499993,   84.499993,   86.499993,   88.499993,
         90.499992,   92.499992,   94.499992,   96.499992,   98.499992,
        100.499992,  102.499992,  104.499992,  106.499992,  108.499992,
        110.499992,  112.499992,  114.499992,  116.499992,  118.499992,
        120.499992,  122.499992,  124.499992,  126.499991,  128.499991,
        130.499991,  132.499991,  134.499991,  136.499991,  138.499991,
        140.499991,  142.499991,  144.499991,  146.499991,  148.499991,
        150.499991,  152.499991,  154.499991,  156.499991,  158.499991,
        160.499991,  162.49999 ,  164.49999 ,  166.49999 ,  168.49999 ,
        170.49999 ,  172.49999 ,  174.49999 ,  176.49999 ,  178.49999 ])
Coordinates:
  * lon      (lon) float64 1kB -179.5 -177.5 -175.5 -173.5 ... 174.5 176.5 178.5

In [ ]:
# ==========================
# 基本参数
# ==========================

R0 = 173 - 40  # 月球半径-平均壳厚 km

DLON = float(moho_grid.lon[1] - moho_grid.lon[0])
DLAT = float(moho_grid.lat[1] - moho_grid.lat[0])

# ==========================
# 球坐标 -> 笛卡尔
# ==========================

def sph2cart(lon_deg, lat_deg, r):

    lon = np.deg2rad(lon_deg)
    lat = np.deg2rad(lat_deg)

    x = r * np.cos(lat) * np.cos(lon)
    y = r * np.cos(lat) * np.sin(lon)
    z = r * np.sin(lat)

    return np.array([x, y, z])


# ==========================
# 球面棱柱体
# ==========================

def spherical_prism(lon1, lon2, lat1, lat2, r1, r2):

    corners = [
        (lon1, lat1),
        (lon2, lat1),
        (lon2, lat2),
        (lon1, lat2)
    ]

    inner = [sph2cart(lon, lat, r1) for lon, lat in corners]
    outer = [sph2cart(lon, lat, r2) for lon, lat in corners]

    verts = np.array(inner + outer)

    faces = []

    # bottom
    faces += [[0,1,2],[0,2,3]]

    # top
    faces += [[4,6,5],[4,7,6]]

    # sides
    sides = [
        [0,1,5,4],
        [1,2,6,5],
        [2,3,7,6],
        [3,0,4,7]
    ]

    for a,b,c,d in sides:
        faces += [[a,b,c],[a,c,d]]

    return verts, np.array(faces)


# ==========================
# colormap
# ==========================

cmap = cm.get_cmap("seismic")

dhs = moho_grid.values.flatten()

norm = colors.Normalize(
    vmin=np.min(dhs),
    vmax=np.max(dhs)
)


# ==========================
# Plotly 图
# ==========================

fig = go.Figure()

# MOS 135E 160E 15N 35N

LONMIN,LONMAX=135,160
LATMIN,LATMAX=15,35

moho_grid=moho_grid.sel(lon=slice(LONMIN,LONMAX),lat=slice(LATMIN,LATMAX))

lons = moho_grid.lon.values
lats = moho_grid.lat.values

length=np.size(lons)*np.size(lats)

index=0
for lon in tqdm(lons,desc="Outer"):
    for lat in tqdm(lats,desc="Inner",leave=False):
        

        dh = moho_grid.sel(lon=lon, lat=lat).item()

        r1 = R0
        r2 = R0 + dh

        r_inner = min(r1, r2)
        r_outer = max(r1, r2)

        verts, faces = spherical_prism(
            lon,
            lon + DLON,
            lat,
            lat + DLAT,
            r_inner,
            r_outer
        )

        x, y, z = verts.T
        i, j, k = faces.T

        # 颜色
        color = cmap(norm(dh))
        color = f"rgb({int(color[0]*255)},{int(color[1]*255)},{int(color[2]*255)})"

        # 棱柱
        fig.add_trace(go.Mesh3d(
            x=x,
            y=y,
            z=z,
            i=i,
            j=j,
            k=k,
            color=color,
            opacity=0.9,
            flatshading=True,
            showlegend=False
        ))

        # ======================
        # edges
        # ======================

        edges = [
            (0,1),(1,2),(2,3),(3,0),
            (4,5),(5,6),(6,7),(7,4),
            (0,4),(1,5),(2,6),(3,7)
        ]

        for a,b in edges:

            fig.add_trace(go.Scatter3d(
                x=[x[a],x[b]],
                y=[y[a],y[b]],
                z=[z[a],z[b]],
                mode="lines",
                line=dict(color="black", width=1),
                showlegend=False,
                hoverinfo="skip"
            ))
            
        index=index+1

# ==========================
# layout
# ==========================

fig.update_layout(

    title="Moho Spherical Prism Model",

    scene=dict(

        xaxis_title="X (km)",
        yaxis_title="Y (km)",
        zaxis_title="Z (km)",

        aspectmode="data"
    )
)

fig.show()

C:\Users\wzp\AppData\Local\Temp\ipykernel_20124\459677160.py:70: MatplotlibDeprecationWarning: The get_cmap function was deprecated in Matplotlib 3.7 and will be removed in 3.11. Use ``matplotlib.colormaps[name]`` or ``matplotlib.colormaps.get_cmap()`` or ``pyplot.get_cmap()`` instead.
  cmap = cm.get_cmap("seismic")


Outer:   0%|          | 0/12 [00:00<?, ?it/s]

Inner:   0%|          | 0/10 [00:00<?, ?it/s]

Inner:   0%|          | 0/10 [00:00<?, ?it/s]

Inner:   0%|          | 0/10 [00:00<?, ?it/s]

Inner:   0%|          | 0/10 [00:00<?, ?it/s]

Inner:   0%|          | 0/10 [00:00<?, ?it/s]

Inner:   0%|          | 0/10 [00:00<?, ?it/s]

Inner:   0%|          | 0/10 [00:00<?, ?it/s]

Inner:   0%|          | 0/10 [00:00<?, ?it/s]

Inner:   0%|          | 0/10 [00:00<?, ?it/s]

Inner:   0%|          | 0/10 [00:00<?, ?it/s]

Inner:   0%|          | 0/10 [00:00<?, ?it/s]

Inner:   0%|          | 0/10 [00:00<?, ?it/s]

In [8]:
moho_grid

<xarray.DataArray (lat: 10, lon: 12)> Size: 960B
array([[-50.76282433, -46.1029815 , -49.31167408, -48.6743871 ,
        -43.41808887, -46.87012926, -41.09948834, -39.62010648,
        -46.8777502 , -40.95857278, -35.77883013, -42.19581866],
       [-50.8698987 , -42.47939439, -49.20416301, -40.73805282,
        -44.04919258, -49.7284452 , -47.93016832, -49.8545423 ,
        -46.14187732, -43.50028346, -39.66425752, -44.25820771],
       [-45.30605197, -48.11135527, -46.91272541, -47.35097002,
        -54.41746849, -56.11469177, -56.04303789, -51.56188785,
        -51.418467  , -45.9018439 , -43.04531484, -34.6451315 ],
       [-45.1516932 , -43.52156805, -45.1102321 , -59.26061458,
        -61.44332182, -51.85996185, -50.09925221, -54.81278708,
        -46.14174642, -52.36517866, -48.52385938, -40.65901565],
       [-41.57623704, -45.36437943, -50.8121276 , -62.8998437 ,
        -23.95962917,  -8.99812239,  -9.67019133, -24.35574062,
        -32.54890177, -45.34963305, -51.58836798, -42.88790538],
       [-46.17706887, -44.02004757, -54.54955832, -58.95090011,
        -13.50259239,  -9.1505772 , -10.37707282, -20.41857241,
        -27.67177486, -44.66554477, -54.26836573, -46.04791206],
       [-45.74914396, -45.10442059, -53.90662152, -58.81614932,
        -43.0347094 , -13.89801239, -17.21546569, -23.17879165,
        -24.32352514, -49.05648622, -55.67585392, -48.67593427],
       [-46.93230994, -48.33523049, -51.71531746, -54.62190108,
        -49.93197887, -43.30488602, -27.03040623, -25.65076018,
        -41.83361986, -52.84659649, -51.27992517, -44.02247389],
       [-43.3450685 , -46.04627516, -49.02149622, -48.27392864,
        -49.53737089, -45.53721606, -46.12917409, -54.21433648,
        -54.79311766, -55.59837751, -46.09375933, -44.94607034],
       [-44.12410657, -44.72588252, -43.04339894, -40.94303749,
        -48.27793946, -53.82229481, -52.07351807, -50.37411973,
        -51.60120715, -48.92803621, -48.17695906, -48.09276222]])
Coordinates:
  * lat      (lat) float64 80B 16.5 18.5 20.5 22.5 24.5 26.5 28.5 30.5 32.5 34.5
  * lon      (lon) float64 96B 136.5 138.5 140.5 142.5 ... 154.5 156.5 158.5

In [7]:
fig.write_html("spherical_prism_interactive.html")